GET http://localhost:3000/event?after=2022-05-25T07:18:48.753Z

###

GET http://localhost:3000/attendance

###

GET http://localhost:3000/event/628a57fb89353ad06c169da9

###

GET http://localhost:3000/event/628a57fb89353ad06c169da9/attendance
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjhhNTc4Nzg5MzUzYWQwNmMxNjlkYTMiLCJleHAiOjE2NTMyMzM2MzczMjQsImlzQWRtaW4iOmZhbHNlfQ.VzqgKYmDIBzXaIh50-Q1n1hlxIlwI7hs-ciQeoFW5VU

###
POST http://localhost:3000/event/628a57fb89353ad06c169da9/attendance
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjhhNTc4Nzg5MzUzYWQwNmMxNjlkYTMiLCJleHAiOjE2NTMyMzM2MzczMjQsImlzQWRtaW4iOmZhbHNlfQ.VzqgKYmDIBzXaIh50-Q1n1hlxIlwI7hs-ciQeoFW5VU


###
GET http://localhost:3000/client/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2Mjc3ZTYwZTcxZjYzMjcyMmYwNTU3OGMiLCJleHAiOjE2NTMxNTQwMjM0NzksImlzQWRtaW4iOnRydWV9.8auMZwGH6iSCWVNBM-ypXos5lG2H_YGXl6zPHfYVFZc


###

POST http://localhost:3000/client/login
Content-Type: application/json

{
    "client_name": "test123",
    "password": "test123"
}

###

POST http://localhost:3000/client/register
Content-Type: application/json

{
    "client_name": "test123",
    "password": "test123",
    "email": "test@gmail.com"
}

###

GET http://localhost:3000/client

###

GET http://localhost:3000/event?lat=46.554650&long=15.645881&dist=10000

###

GET http://localhost:3000/client

###

GET http://localhost:3000/client/6277d6f080d08b0d4751c499

###

DELETE http://localhost:3000/client/6277d6f080d08b0d4751c499
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjhhNTc4Nzg5MzUzYWQwNmMxNjlkYTMiLCJleHAiOjE2NTMyMzM2MzczMjQsImlzQWRtaW4iOmZhbHNlfQ.VzqgKYmDIBzXaIh50-Q1n1hlxIlwI7hs-ciQeoFW5VU


###

POST http://localhost:3000/infrastructure
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2Mjc3ZTYwZTcxZjYzMjcyMmYwNTU3OGMiLCJleHAiOjE2NTIwMjUyMjUwNjUsImlzQWRtaW4iOnRydWV9.E9PyCoATKlzIXsBEcEQgSLsBnFu2waFSD7xdlBgxfk0

{
    "title": "Stuk",
    "type": "bar",
    "tags": ["party", "club", "bar"],
    "address": "Gosposvetska cesta 83, Maribor, SI 2000",
    "location": {
        "type": "Point",
        "coordinates": [46.55372, 15.64767]
    }
}

###

GET http://localhost:3000/infrastructure
###

GET http://localhost:3000/infrastructure/6277d34b9c4418f95a064f9c

###

DELETE http://localhost:3000/infrastructure/6277d34b9c4418f95a064f9c
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjhhNTc4Nzg5MzUzYWQwNmMxNjlkYTMiLCJleHAiOjE2NTMyMzM2MzczMjQsImlzQWRtaW4iOmZhbHNlfQ.VzqgKYmDIBzXaIh50-Q1n1hlxIlwI7hs-ciQeoFW5VU


###

POST http://localhost:3000/event
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjhhNTc4Nzg5MzUzYWQwNmMxNjlkYTMiLCJleHAiOjE2NTMyMzM2MzczMjQsImlzQWRtaW4iOmZhbHNlfQ.VzqgKYmDIBzXaIh50-Q1n1hlxIlwI7hs-ciQeoFW5VU

{
    "title": "Sodobna slovenska ilustracija",
    "description": "Razstava 14. Slovenskega bienala ilustracije.",
    "location": {
        "type": "Point",
        "coordinates": [
            46.55865,
            15.64196
        ]
    },
    "organization": "Umetnostna galerija Maribor",
    "contact": "info@ugm.si",
    "price": "Vstopnina od 3,00\u20ac do 5,00\u20ac",
    "tags": [
        "Razstava"
    ],
    "link": "http://www.ugm.si/razstave/sodobna-slovenska-ilustracija-4688/",
    "image": "https://www.visitmaribor.si/DownloadedEventImages/form/6e67303c-dad4-431e-aea8-b4937ed039ab.jpg?anchor=center&mode=crop&width=640&height=480&quality=95",
    "date_start": "2022-05-23T14:18:48.753Z",
    "date_end": "2022-05-25T06:18:48.753Z"
}

###

GET http://localhost:3000/event

###

GET http://localhost:3000/event/628a57fb89353ad06c169da9

###
DELETE http://localhost:3000/event/6277afdd6b409056359b1676
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjhhNTc4Nzg5MzUzYWQwNmMxNjlkYTMiLCJleHAiOjE2NTMyMzM2MzczMjQsImlzQWRtaW4iOmZhbHNlfQ.VzqgKYmDIBzXaIh50-Q1n1hlxIlwI7hs-ciQeoFW5VU
